---
- name: Generate ssh
  shell: "ssh-keygen -q -t rsa -N '' -f /tmp/ansible_id_rsa <<<y >/dev/null 2>&1"

- name: Create User
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    shell: /bin/bash
    groups: "{{ super_group }}"
    append: yes

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '/tmp/ansible_id_rsa.pub') }}"

