---
- debug:
    msg: "Hello from your external use case!"

- include_role:
    name: "microk8s"

- include_role:
    name: "dt-oneagent-classic"

- include_role:
    name: "app-easytravel-classic"

- include_role:
    name: gitea

- include_role:
    name: gitea
    tasks_from: source-secret
  when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "{{ demo_auto_remediation_org }}"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ demo_auto_remediation_org }}"
    gitea_repo: "{{ demo_auto_remediation_repo_name }}"

- include_role:
    name: repository
  vars:
    repo_src: "{{ item.repo_src }}"
    git_org: "{{ item.git_org }}"
    git_repo: "{{ item.repo_target }}"
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_domain: "{{ gitea_domain }}"
    git_remote: "gitea"
  loop:
  - { repo_target: "{{ demo_auto_remediation_repo_name }}", repo_src: "{{ role_path }}/files/repos/autoremediation-demo", git_org: "{{ demo_auto_remediation_org }}" }
  when: new_repo_created is defined and new_repo_created == true

- include_role:
    name: awx-cust
    tasks_from: create-secrets

- include_role:
    name: "awx-cust"