---
- name: Source private IP
  command: "ip addr show dev ens4 | grep 'inet ' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'"
  register: private_output

- name: Set facts
  set_fact:
    ace_box_private_ip: "{{ private_output.stdout }}"