---
- name: Create namespace for AWX
  kubernetes.core.k8s:
    name: "{{ awx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: awx-operator
    repo_url: "https://ansible.github.io/awx-operator/"

- name: Gitlab - Template values file
  ansible.builtin.template:
    src: awx-operator-values.yml.j2
    dest: "./roles/{{ role_name }}/files/awx-operator-values.yml"
    owner: "{{ ace_box_user }}"
    group: "{{ ace_box_user }}"
    mode: '0644'

- name: Install
  kubernetes.core.helm:
    name: awx
    chart_ref: awx-operator/awx-operator
    chart_version: "{{ awx_helm_chart_version }}"
    release_namespace: "{{ awx_namespace }}"
    create_namespace: true
    wait: true
    wait_timeout: 15m
    values_files:
      - "./roles/{{ role_name }}/files/awx-operator-values.yml"
  register: awx_helm