---
- name: Create namespace for AWX
  kubernetes.core.k8s:
    name: "{{ awx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create AWX admin secret
  kubernetes.core.k8s:
    name: "{{ awx_admin_creds_secret_name }}"
    api_version: v1
    kind: Secret
    state: present
    namespace: "{{ awx_namespace }}"
    resource_definition:
      type: Opaque
      data:
        AWX_ADMIN_USER: "{{ awx_admin_user | b64encode }}"
        AWX_ADMIN_PASSWORD: "{{ awx_admin_password | b64encode }}"

- name: Create AWX secret key secret
  kubernetes.core.k8s:
    name: "{{ awx_secret_key_secret_name }}"
    api_version: v1
    kind: Secret
    state: present
    namespace: "{{ awx_namespace }}"
    resource_definition:
      type: Opaque
      data:
        SECRET_KEY: "{{ 'dynatrace' | b64encode }}"
