---
- name: Source AWX admin creds secret
  kubernetes.core.k8s_info:
    kind: Secret
    name: "awx-admin-creds"
    namespace: "{{ awx_namespace }}"
  register: awx_admin_creds_data

- name: Set secrets facts
  set_fact:
    awx_admin_username: "{{ awx_admin_creds_data.resources[0].data.AWX_ADMIN_USER | b64decode }}"
    awx_admin_password: "{{ awx_admin_creds_data.resources[0].data.AWX_ADMIN_PASSWORD | b64decode }}"
  when: awx_admin_creds_data is defined and awx_admin_creds_data.resources[0] is defined
