---
- name: Source endpoints
  kubernetes.core.k8s_info:
    kind: Service
    name: "awx"
    namespace: "{{ awx_namespace }}"
  register: awx_data

- name: Set facts
  set_fact:
    awx_internal_endpoint: "http://{{ awx_data.resources[0].spec.clusterIP }}:8080"
  when: awx_data is defined and awx_data.resources[0] is defined
